---
- name: Install Nginx
  hosts: all
  become: yes
  tasks:
    - name: Install Nginx on Amazon Linux
      when: ansible_distribution == 'Amazon'
      yum:
        name: nginx
        state: present

    - name: Install Nginx on Ubuntu
      when: ansible_distribution == 'Ubuntu'
      apt:
        name: nginx
        state: present
